### ISSUE TITLE
v4.0.0 Roadmap (2019)

### ISSUE THREAD

**Issue by pgoldrbx** [CondeNast/copilot-util#66]
### Breaking
- [x] Drop support for older node versions (< node 10) (#74, #86 )
- [x] Use native `Promise` and remove `bluebird` (tested in #71, done in #83 )
- [x] Remove exported `Promise` (#83)
- [x] Remove exported `collection` property and remove `immutable` (plan https://github.com/CondeNast/copilot-util/issues/66#issuecomment-527662765) (PR: https://github.com/CondeNast/copilot-util/pull/85)

---

Additional changes can be made before or after the major version release:

### Updates
- [x] Update `agentkeepalive` to v4 (may not require a breaking change) (#65) (reviewed and commented https://github.com/CondeNast/copilot-util/pull/65#issuecomment-527660689)
- [ ] ~Refactor to `async`/`await`~ (will do this in the future)

### Chores
- [ ] Update and improve documentation
- [x] Run tests against node ~8,~ 10, 12 (#75, #76, #86)

**Comment by tollmanz** [comment]
I've updated this issue to have checkboxes and have started to annotate the items with corresponding PR/Issue numbers.

**Comment by tollmanz** [comment]
To remove `immutable`, it looks like we'd need to do the following:

* Update internal references (very few and all are simple to update)
* Update `copilot-js-sdk` as part of a major upgrade. It exports `sdk.core.collection` which depends on `core.collection`. We can time this with the major update work we plan to do with `copilot-hal` for `copilot-js-sdk`
* Announce loudly that this feature is deprecated

I've searched Github and found no references to `core.collection` outside of `copilot-util` and `copilot-js-sdk`. Certainly, it may be used in hard to find ways, which is fine if we announce the deprecation appropriately.

**Comment by pgoldrbx** [comment]
I'm pretty confident it is not used

**Comment by pgoldrbx** [comment]
Thoughts on setting minimum node version to 10.x?

**Comment by tollmanz** [comment]
> Thoughts on setting minimum node version to 10.x?

Do it!
